name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: pip install -r requirements.txt
#    - run: pytest
    - name: Run tests
      run: |
        pytest tests/
      env:
        PYTHONPATH: ${{ github.workspace }}

    - name: Close Stale Issues
      uses: actions/stale@v4.1.1

    - name: KiBot GitHub action
      uses: INTI-CMNB/KiBot@v2_k7


#    - name: Install dependencies
#      run: pip install flake8
#    - run: flake8
